main: com.codekova.loreplacer.LoReplacer
name: LoReplacer
version: 1.2
author: CodeKova
commands:
  loreplace:
    description: Show LoReplacer commands.
    permission: loreplace.admin
    usage: /<command>
    aliases: lr
